module.exports = [{
  body: {
    type: 'single-family home',
    street: '109 W Walnut St',
    city: 'Tolono',
    state: 'IL',
    zip: '61880',
    stories: '1',
    rent: '1080.00',
    occupied: 'true',
    occupants: '2',
    sqft: '1500',
    year: '1965',
    washer: 'false',
    dryer: 'false',
    garage: 'false',
    basement: 'false',
    fence: 'true',
  }
},{
  body: {
    type: 'single-family home',
    street: '110 W Walnut St',
    city: 'Tolono',
    state: 'IL',
    zip: '61880',
    stories: '1',
    rent: '1200.00',
    occupied: 'false',
    occupants: '0',
    sqft: '1600',
    year: '1962',
    washer: 'false',
    dryer: 'false',
    garage: 'false',
    basement: 'false',
    fence: 'true',
  }
},{
  body: {
    type: 'condominium',
    street: '111 W Walnut St',
    city: 'Tolono',
    state: 'IL',
    zip: '61880',
    stories: '3',
    rent: '1500.00',
    occupied: 'true',
    occupants: '3',
    sqft: '1900',
    year: '1982',
    washer: 'true',
    dryer: 'true',
    garage: 'true',
    basement: 'false',
    fence: 'true',
  }
},{
  body: {
    type: 'duplex',
    street: '112 W Walnut St',
    city: 'Champaign',
    state: 'IL',
    zip: '61820',
    stories: '1',
    rent: '850.00',
    occupied: 'true',
    occupants: '2',
    sqft: '1200',
    year: '1943',
    washer: 'false',
    dryer: 'false',
    garage: 'true',
    basement: 'false',
    fence: 'true',
  }
},{
  body: {
    type: 'studio',
    street: '113 W Walnut St',
    city: 'Tolono',
    state: 'IL',
    zip: '61880',
    stories: '1',
    rent: '750.00',
    occupied: 'true',
    occupants: '1',
    sqft: '950',
    year: '1990',
    washer: 'true',
    dryer: 'true',
    garage: 'false',
    basement: 'false',
    fence: 'false',
  }
}];
